name: Generate Project List

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  creations_stats_job:
    name: Update profile with recent repositories and gists
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

        # Generate repos in a minimal style
      - name: Generate Repos with Minimal style
        uses: ArsenTech/creations-stats-workflow@v1.0.2
        with:
          github-username: ArsenTech
          exclusions: ArsenTech,source-codes
          target-file: test.md
          repo-tag-name: MINIMAL
          repo-list-design: minimal
          commit-message: "[AUTOMATED-CHANGE]: Updated Repository stats using a minimal design"

        # Generate repos in a detailed style
      - name: Generate Repos with Detailed style
        uses: ArsenTech/creations-stats-workflow@v1.0.2
        with:
          github-username: ArsenTech
          exclusions: ArsenTech,source-codes
          target-file: test.md
          repo-tag-name: DETAILED
          repo-list-design: detailed
          commit-message: "[AUTOMATED-CHANGE]: Updated Repository stats using a detailed design"

        # Generate gists only
      - name: Generate Gists
        uses: ArsenTech/creations-stats-workflow@v1.0.2
        with:
          github-username: ArsenTech
          target-file: test.md
          repo-tag-name: ""
          commit-message: "[AUTOMATED-CHANGE]: Updated Gist stats"